version: '2'

services:

### Workspace Utilities Container ###########################

    workspace:
        build:
            context: ./${DOCKER_DIRECTORY}/workspace
            args:
                - INSTALL_XDEBUG
                - INSTALL_MONGO
                - COMPOSER_GLOBAL_INSTALL
                - PUID=1000
                - PGID=1000
        volumes_from:
            - volumes_source
        extra_hosts:
            # IMPORTANT: Replace with your Docker Host IP (will be appended to /etc/hosts)
            - "mongocli:10.0.3.1"
        tty: true

### PHP-FPM Container #######################################

    php-fpm:
        build:
            context: ./${DOCKER_DIRECTORY}/php-fpm
            args:
                - INSTALL_XDEBUG
                - INSTALL_MONGO
            dockerfile: ${PHP_DOCKERFILE}
        volumes_from:
            - volumes_source
        expose:
            - "9000"
        links:
            - workspace
        extra_hosts:
            # IMPORTANT: Replace with your Docker Host IP (will be appended to /etc/hosts)
            - "mongocli:10.0.3.1"
        environment:
            # IMPORTANT: Set the Remote Interpreter entry matching name to `laravel`
            - PHP_IDE_CONFIG="serverName=laravel"

### Apache Server Container ##################################

    apache2:
        build:
            context: ./${DOCKER_DIRECTORY}/apache2
            args:
                - PHP_SOCKET=php-fpm:9000
                - PROJECT_SUBDIRECTORY
        volumes_from:
            - volumes_source
        volumes:
            - ./${DOCKER_DIRECTORY}/logs/apache2:/var/log/apache2
        ports:
            - "${HTTP_PORT}:80"
            - "${HTTPS_PORT}:443"
        links:
            - php-fpm

### MongoDB Container #######################################

    mongo:
        build:
            context: ./${DOCKER_DIRECTORY}/mongo
            dockerfile: ${MONGODB_DOCKERFILE}
        ports:
            - "${MONGODB_PORT}:27017"
        volumes_from:
            - volumes_data

### Application Code Container ######################

    volumes_source:
        image: tianon/true
        volumes:
            - ./${PROJECT_DIRECTORY}:/var/www/
            # Demonstration of how to mount multiple sites
#             - ./${PROJECT_DIRECTORY}/project_one:/var/www/project_one
#             - ./${PROJECT_DIRECTORY}/project_two:/var/www/project_two

### Databases Data Container ################################

    volumes_data:
        image: tianon/true
        volumes:
            - ./${DOCKER_DATA_DIRECTORY}/mongo:/data/db
            - ./${DOCKER_DATA_DIRECTORY}/sessions:/sessions

### Add more Containers below ###############################
